### ISSUE TITLE
Homeyscript integration stops working for me after a day or so

### ISSUE THREAD

**Issue by WBDN2** [Erikvl87/nl.erikvl87.todoist#1]
I have made a script which uses your app. After the app has run for a day or so it stops working. The script returns "Service Unavailable"
———————————————————
❌ Script Error
⚠️ Service Unavailable
: Service Unavailable

    at /node_modules/athom-api/dist/index.js:1:1247257
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Tried to isolate what api call that causes it and I get it when fetching the projects:
const projects = await app.apiGet(`/users/${userId}/projects`);

(though getting the user works okay)

Restarting the app and then it works again.

**Comment by jeroenwienk** [comment]
> I have made a script which uses your app. After the app has run for a day or so it stops working. The script returns "Service Unavailable" ——————————————————— ❌ Script Error ⚠️ Service Unavailable : Service Unavailable
> 
> ```
> at /node_modules/athom-api/dist/index.js:1:1247257
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> Tried to isolate what api call that causes it and I get it when fetching the projects: const projects = await app.apiGet(`/users/${userId}/projects`);
> 
> (though getting the user works okay)
> 
> Restarting the app and then it works again.

Sorry I've missed this issue but is it still present? Also how many times is this Flow executed? Maybe it's a rate limit issue.

**Comment by WBDN2** [comment]
Roughly 1-2 times per hour + maybe 3 times per day max.
I now restart the app every day to workaround this issue.
